import React from 'react';
import LocalizedStrings from 'react-native-localization';


const strings = new LocalizedStrings({
    'en-US':{
        
        submit: "Submit",
        gsmnumber: 'GSM Number',
        confirmation:'confirmation',
        enteryourcodehere:'Enter Your Code Here',
        confirm:'confirm',
        takeaway: 'Take Away',
        delivery: 'Delivery',
        home: 'Home',
        pizzatracker: 'Pizza Tracker',
        Location: 'LOCATION',
        open:'Open',
        waitingtime:'WAITING TIME',
        fullname:'FULL NAME',
        address:'ADDRESS',
        comments:'COMMENTS',
        savedetailfornextorder:'Save detail for next order',
        next:'NEXT',
        typeyournamehere:'Type your name here',
        typeyourcompleteaddress:'Type your complete address',
        typeyourlocation:'Type your location',
        typeyourcommentshere:'Type your comments here',
        lastorder: 'Last Order',
        offer:'OFFER',
        makeyourownpizza:'Make your own pizza',
        selectcategory:'SELECT CATEGORY',
        addtoorder:'Add to order',
        selectsize:'Select Size',
        choosesize: 'CHOOSE SIZE',
        choosebottom: 'Choose Bottom',
        small:'Small',
        medium:'Medium',
        large:'Large',
        makeyourown:'MAKE YOUR OWN',
        startbychossingsize:'START BY CHOOSING THE SIZE YOUR WANT',
        total:'Total',
        startbychossingbottom:'START BY CHOOSING THE BOTTOM YOUR WANT',
        nowchosseyourtoppings:'NOW CHOOSE YOUR TOPPINGS',
        choosefrommenu:'CHOOSE FROM MENU',
        iamcreatemyown:'I am going to create my own',
        splitinhalf: 'Split in half',
        firsthalf:'FIRST HALF',
        secondhalf: 'SECOND HALF',
        cancelsplit: 'Cancel split',
        meat: 'MEAT',
        vegetables : 'VEGETABLES',
        cheese: 'CHEESE',
        spicesauses: 'SPICES & SAUSES',
        addtocart: 'Add to cart',
        footerlocation: 'Location',
        tracker:'Pizza-Tracker',
        location:'Location',
        otpsendmessage:'Otp has sent to your registered mobile no.'
        
      },
  
    "is-IS":{
    
        submit: "leggja fram",
        gsmnumber:'GSM númer',
        confirmation:'staðfesting',
        enteryourcodehere:'Sláðu inn kóðann þinn hér',
        confirm:'staðfesta',
        takeaway: 'Taka í burtu',
        delivery: 'Afhending',
        home: 'Heim',
        pizzatracker: 'Pizzakóngur',
        Location: 'Staðsetning',
        open:'Opið',
        waitingtime:'Biðtími',
        fullname:'FULLT NAFN',
        address:'ADDRESS',
        comments:'Athugasemdir',
        savedetailfornextorder:'Vistaðu smáatriði fyrir næstu pöntun',
        next:'NÆSTU',
        typeyournamehere:'Sláðu inn nafnið þitt hér',
        typeyourcompleteaddress:'Sláðu inn heill heimilisfang þitt',
        typeyourlocation:'Sláðu inn staðsetningu þína',
        typeyourcommentshere:'Sláðu inn athugasemdir þínar hér',
        lastorder: 'Síðasta pöntun',
        offer:'Tilboð',
        makeyourownpizza:'Búðu til þína eigin pizzu',
        selectcategory:'VELJA FLOKKUR',
        addtoorder:'Bæta við pöntun',
        selectsize:'Veldu Stærð',
        choosesize: 'Veldu stærð',
        choosebottom: 'Veldu botn',
        small:'Lítil',
        medium:'Miðlungs',
        large:'Stór',
        makeyourown:'Gerðu þitt eigið',
        startbychossingsize:'Byrjaðu með því að velja stærðina sem þú vilt',
        total:'Samtals',
        startbychossingbottom:'Byrjaðu með því að velja BOTTOMINU ÞÉR VILJA',
        nowchosseyourtoppings:'NÚNA VELJA ÁFANGI ÞITTA',
        choosefrommenu:'VELJA FRÁ MENU',
        iamcreatemyown:'Ég ætla að búa til mitt eigið',
        splitinhalf: 'Skiptist í tvennt',
        firsthalf:'FYRSTI HELMINGUR',
        secondhalf: 'SEINNI HELMINGUR',
        cancelsplit: 'Hætta við skiptingu',
        meat: 'Kjöt',
        vegetables : 'Grænmeti',
        cheese: 'KAFLI',
        spicesauses: 'Krydd og sósur',
        addtocart: 'Bæta í körfu',
        footerlocation:'Staðsetning',
        tracker:'Pizza-Tracker',
        location:'Staðsetning',
        otpsendmessage:'Otp hefur sent á skráða farsímann þinn.'


  },
  
});
export default strings;